import {useEffect,useRef,useState} from 'react';
import Panzoom,{type PanzoomObject} from '@panzoom/panzoom';
import {basemap,imageAnchors} from '../data/basemap';
import {places as publishedPlaces,relations,works} from '../data/content';
import {MapControls} from './MapControls';
import {CategoryIcon} from './CategoryIcon';
import {shortQuote,overviewFocus} from '../data/visual';
import {preferredWork} from '../data/exploration';
import type {SearchResult} from '../data/catalog';
import {clusters,collides,fittedImage,focusCamera,projectAnchor,resizedCamera,MIN_SCALE,MAX_SCALE,type Camera,type Size} from '../map/overview-math';
import {mapReadingArea,type ReaderLayout} from '../layout/reader-layout';
type Group={id:string;ids:string[];label:string};
export function OverviewViewport({selected,workId,expanded,layout,local,reduced,results,onSelect,onRead,layoutData}:{selected:string|null;workId:string;expanded:boolean;layout?:ReaderLayout;local:boolean;reduced:boolean;results:SearchResult[];onSelect:(id:string,work?:string)=>void;onRead:()=>void;layoutData?:{places:typeof publishedPlaces;anchors:typeof imageAnchors}}){
 function groupLabel(regions:string[]){const cities=regions.map(r=>r.split('·').at(-1)!.trim()),provinces=regions.map(r=>r.split('·')[0].trim());if(new Set(cities).size===1)return cities[0];if(new Set(provinces).size===1)return provinces[0];if(provinces.every(r=>['江苏','浙江'].includes(r)))return '江南';return '近邻';}
 const places=layoutData?.places??publishedPlaces,anchors=layoutData?.anchors??imageAnchors;
 const frame=useRef<HTMLDivElement>(null),plane=useRef<HTMLDivElement>(null),pz=useRef<PanzoomObject|null>(null);
 const camera=useRef<Camera>({x:0,y:0,scale:1}),saved=useRef<Camera|null>(null),readingCamera=useRef<Camera|null>(null),size=useRef<Size>({width:1,height:1});
 const previous=useRef({selected:null as string|null,local:false,expanded:false});
 const latest=useRef({selected,expanded,layout,local,reduced,results,onSelect});latest.current={selected,expanded,layout,local,reduced,results,onSelect};
 const [groups,setGroups]=useState<Group[]>([]),[chooser,setChooser]=useState<string[]|null>(null),[preview,setPreview]=useState<string|null>(null),[failed,setFailed]=useState(false),[original,setOriginal]=useState(false);
 const displayed=useRef<Camera>({x:0,y:0,scale:1});const groupTrigger=useRef<HTMLElement|null>(null);
 const trace=useRef<{t:number;dt:number;error:number;scale:number}[]>([]);const traceEnabled=new URLSearchParams(location.search).has('motionTrace');
 const signature=useRef(''),raf=useRef(0),animateUntil=useRef(0),drag=useRef({x:0,y:0,moved:false,active:false}),suppress=useRef(0),request=useRef(0);
 const sync=useRef<()=>void>(()=>{});
 const layoutRaf=useRef(0),avoidPending=useRef(false);
 const userCamera=useRef(false);
 function readingSpace(){return frame.current?mapReadingArea(frame.current):{left:0,top:0,width:0,height:0};}
 function avoidPaper(){const parent=frame.current,a=anchors.find(a=>a.placeId===latest.current.selected);if(!parent||!a||latest.current.local||userCamera.current||drag.current.active||document.querySelector('.app[data-directory-open="true"]')||document.querySelector('.reading-sheet[data-reader-motion="moving"],.reading-sheet[data-reader-motion="dragging"]')||(latest.current.expanded&&latest.current.layout?.type==='bottom'))return;if(performance.now()<animateUntil.current){avoidPending.current=true;return;}const area=readingSpace();if(area.width<130||area.height<100)return;const c=visualCamera(),point=projectAnchor(a,size.current,basemap,c);const target={x:Math.max(area.left+55,Math.min(point.x,area.left+area.width-55)),y:Math.max(area.top+75,Math.min(point.y,area.top+area.height-35))};if(Math.hypot(point.x-target.x,point.y-target.y)>1)move(focusCamera(a,size.current,basemap,target,c.scale),false);}
 sync.current=()=>{const el=plane.current,parent=frame.current;if(!el||!parent||!parent.getClientRects().length)return;const matrix=new DOMMatrixReadOnly(getComputedStyle(el).transform);const c={scale:matrix.a||1,x:matrix.e/(matrix.a||1),y:matrix.f/(matrix.a||1)};displayed.current={...c};const ids=latest.current.results.map(r=>r.place.id);if(latest.current.selected&&!ids.includes(latest.current.selected))ids.push(latest.current.selected);const visible=ids.map(id=>{const a=anchors.find(a=>a.placeId===id)!;return {...projectAnchor(a,size.current,basemap,c),id};});
  // Current reading keeps its own entry, including at a shared city anchor.
  const selectedPoint=visible.find(p=>p.id===latest.current.selected);
  const next:Group[]=clusters(visible.filter(p=>p.id!==latest.current.selected)).map(g=>({id:g.map(p=>p.id).sort().join('-'),ids:g.map(p=>p.id),label:g.length===1?places.find(p=>p.id===g[0].id)!.name:groupLabel(g.map(p=>places.find(q=>q.id===p.id)!.region))}));
  if(selectedPoint)next.unshift({id:selectedPoint.id,ids:[selectedPoint.id],label:places.find(p=>p.id===selectedPoint.id)!.name});
  const sig=next.map(g=>g.id).join('|');if(sig!==signature.current){signature.current=sig;setGroups(next);}
  const parentRect=parent.getBoundingClientRect();const controls=parent.querySelector('.overview-controls')?.getBoundingClientRect();
  const occupied:{x:number;y:number;width:number;height:number}[]=controls?[{x:controls.x-parentRect.x+controls.width/2,y:controls.y-parentRect.y+controls.height/2,width:controls.width,height:controls.height}]:[];
  const directory=document.querySelector<HTMLElement>('#directory');if(directory&&directory.getAttribute('aria-modal')!=='true'){const r=directory.getBoundingClientRect();occupied.push({x:r.x-parentRect.x+r.width/2,y:r.y-parentRect.y+r.height/2,width:r.width,height:r.height});}
  for(const group of next){const first=visible.find(p=>p.id===group.ids[0])!;const marker=parent.querySelector<HTMLElement>(`[data-entry-id="${group.id}"]`);if(!marker)continue;const w=marker.offsetWidth||100,h=44;let pos={x:first.x+w/2+9,y:first.y};const candidates=[pos,{x:first.x-w/2-9,y:first.y},{x:first.x,y:first.y-31},{x:first.x,y:first.y+31},{x:first.x-w/2,y:first.y-55},{x:first.x+w/2,y:first.y+55}];
   const {left:safeLeft,top:safeTop,width:safeWidth,height:safeHeight}=readingSpace();
   // Prefer the current name. A crowded neighbour searches real free space,
   // instead of clamping back over the already placed selected label.
   const free=(p:{x:number;y:number})=>p.x-w/2>=safeLeft+6&&p.x+w/2<=safeLeft+safeWidth-6&&p.y-h/2>=safeTop+8&&p.y+h/2<=safeTop+safeHeight-8&&!occupied.some(q=>collides({...p,width:w,height:h},q));
   const alternatives:{x:number;y:number}[]=[];for(let y=safeTop+h/2+8;y<=safeTop+safeHeight-h/2-8;y+=h+8)for(let x=safeLeft+w/2+6;x<=safeLeft+safeWidth-w/2-6;x+=30)alternatives.push({x,y});
   const found=candidates.find(free)??alternatives.sort((a,b)=>Math.hypot(a.x-first.x,a.y-first.y)-Math.hypot(b.x-first.x,b.y-first.y)).find(free);
   pos=found??{x:w/2+6,y:h/2+8};
   marker.style.left=`${pos.x}px`;marker.style.top=`${pos.y}px`;marker.dataset.screenX=String(first.x);marker.dataset.screenY=String(first.y);const hidden=!found||first.x<0||first.y<0||first.x>size.current.width||first.y>size.current.height;marker.style.visibility=hidden?'hidden':'';if(!hidden)occupied.push({...pos,width:w,height:h});
   const leader=parent.querySelector<SVGPathElement>(`[data-label-leader="${group.id}"]`);const end={x:Math.max(pos.x-w/2,Math.min(first.x,pos.x+w/2)),y:Math.max(pos.y-h/2,Math.min(first.y,pos.y+h/2))};leader?.setAttribute('d',!hidden&&Math.hypot(first.x-end.x,first.y-end.y)>22?`M${first.x},${first.y}L${end.x},${end.y}`:'');
  }
  for(const p of visible){const dot=parent.querySelector<HTMLElement>(`[data-anchor="${p.id}"]`);if(dot){dot.style.left=`${p.x}px`;dot.style.top=`${p.y}px`;}}
  const list=parent.querySelector<HTMLElement>('.map-place-list');if(list){const area=readingSpace();list.style.maxHeight=`${Math.max(44,area.top+area.height-55-8)}px`;list.style.width=`${Math.max(100,Math.min(315,area.width-16))}px`;}
  const poem=parent.querySelector<HTMLElement>('.map-poem-preview');const target=visible.find(p=>p.id===poem?.dataset.previewId);const guide=parent.querySelector<SVGPathElement>('.poem-leader');
  if(poem&&target){const {left:safeLeft,top:safeTop,width:safeWidth,height:safeHeight}=readingSpace();const w=poem.offsetWidth,h=poem.offsetHeight;
   const options=[{x:target.x+32,y:target.y+38},{x:target.x-w-28,y:target.y+38},{x:target.x-w/2,y:target.y-h-38}];const box=options.map(p=>({x:Math.max(8,Math.min(p.x,safeWidth-w-8)),y:Math.max(54,Math.min(p.y,safeHeight-h-8))})).find(p=>!occupied.some(q=>collides({x:p.x+w/2,y:p.y+h/2,width:w,height:h},q)))??{x:Math.max(8,Math.min(target.x-w/2,safeWidth-w-8)),y:Math.max(54,safeHeight-h-8)};
   poem.style.left=`${box.x}px`;poem.style.top=`${box.y}px`;poem.style.visibility=latest.current.expanded&&latest.current.layout?.type==='bottom'?'hidden':'visible';
   const end={x:Math.max(box.x,Math.min(target.x,box.x+w)),y:Math.max(box.y,Math.min(target.y,box.y+h))};guide?.setAttribute('d',`M${target.x},${target.y}L${end.x},${end.y}`);
  }else guide?.setAttribute('d','');
  parent.dataset.motionState=performance.now()<animateUntil.current?'moving':'idle';parent.dataset.camera=JSON.stringify(camera.current);parent.dataset.savedCamera=JSON.stringify(saved.current);parent.dataset.readingCamera=JSON.stringify(readingCamera.current);parent.dataset.safeArea=JSON.stringify(readingSpace());parent.dataset.groups=next.map(g=>g.ids.join(',')).join('|');parent.dispatchEvent(new Event('map-annotations'));
  if(traceEnabled){const now=performance.now(),image=el.querySelector('img')?.getBoundingClientRect(),dot=parent.querySelector<HTMLElement>(`[data-anchor="${latest.current.selected}"]`)?.getBoundingClientRect(),a=anchors.find(p=>p.placeId===latest.current.selected);const error=image&&dot&&a?Math.hypot(dot.x+dot.width/2-image.x-a.x/basemap.width*image.width,dot.y+dot.height/2-image.y-a.y/basemap.height*image.height):0;const last=trace.current.at(-1);trace.current.push({t:now,dt:last?now-last.t:0,error,scale:c.scale});if(trace.current.length>240)trace.current.shift();parent.dataset.motionFrames=JSON.stringify(trace.current);}
  if(performance.now()<animateUntil.current)raf.current=requestAnimationFrame(()=>sync.current());else if(avoidPending.current){avoidPending.current=false;avoidPaper();}
 };
 function visualCamera(){const el=plane.current;if(!el)return camera.current;const m=new DOMMatrixReadOnly(getComputedStyle(el).transform);return {scale:m.a||1,x:m.e/(m.a||1),y:m.f/(m.a||1)};}
 function move(c:Camera,animated=true){const n=++request.current,api=pz.current;if(!api)return;const animate=animated&&!latest.current.reduced&&!matchMedia('(prefers-reduced-motion: reduce)').matches;camera.current=c;animateUntil.current=performance.now()+(animate?450:0);
  const setTransform=(el:HTMLElement|SVGElement,v:{x:number;y:number;scale:number})=>{if(n!==request.current)return;el.style.transform=`scale(${v.scale}) translate(${v.x}px, ${v.y}px)`;};
  api.zoom(c.scale,{animate,duration:420,setTransform});requestAnimationFrame(()=>{if(n!==request.current)return;api.pan(c.x,c.y,{animate,duration:420,setTransform});cancelAnimationFrame(raf.current);raf.current=requestAnimationFrame(()=>sync.current());});}
 function takeOver(){userCamera.current=true;cancelAnimationFrame(layoutRaf.current);avoidPending.current=false;const c=visualCamera(),n=++request.current,api=pz.current;if(!api)return;animateUntil.current=0;camera.current=c;plane.current!.style.transition='none';plane.current!.style.transform=`scale(${c.scale}) translate(${c.x}px, ${c.y}px)`;const setTransform=(el:HTMLElement|SVGElement,v:{x:number;y:number;scale:number})=>{if(n===request.current){el.style.transition='none';el.style.transform=`scale(${v.scale}) translate(${v.x}px, ${v.y}px)`;}};api.zoom(c.scale,{animate:false,setTransform});api.pan(c.x,c.y,{animate:false,setTransform});}
 function closeChooser(){setChooser(null);const trigger=groupTrigger.current;requestAnimationFrame(()=>{if(trigger?.isConnected&&getComputedStyle(trigger).visibility!=='hidden')trigger.focus({preventScroll:true});else document.querySelector<HTMLButtonElement>('[aria-controls="directory"]')?.focus({preventScroll:true});});}
 function focus(id:string){userCamera.current=false;const a=anchors.find(a=>a.placeId===id);if(!a)return;const s=size.current,area=readingSpace();const target={x:area.left+area.width*.48,y:Math.max(area.top+75,area.top+area.height*.48)};move(focusCamera(a,s,basemap,target,Math.max(camera.current.scale,latest.current.layout?.type==='bottom'?overviewFocus.bottom:overviewFocus.side)));}
 function pick(r:SearchResult){if(performance.now()<suppress.current)return;setChooser(null);setPreview(null);latest.current.onSelect(r.place.id,preferredWork(r,relations));}
 useEffect(()=>{const el=plane.current,parent=frame.current;if(!el||!parent)return;size.current={width:parent.clientWidth,height:parent.clientHeight};const fit=()=>{const f=fittedImage(size.current,basemap);const image=el.querySelector('img')!;Object.assign(image.style,{width:`${f.width}px`,height:`${f.height}px`,left:`${f.left}px`,top:`${f.top}px`});};fit();
  const api=Panzoom(el,{canvas:true,minScale:MIN_SCALE,maxScale:MAX_SCALE,startScale:1,pinchAndPan:true,excludeClass:'panzoom-exclude',duration:420,step:.3});pz.current=api;
  const change=()=>{camera.current={...api.getPan(),scale:api.getScale()};const seconds=parseFloat(getComputedStyle(el).transitionDuration)||0;if(seconds)animateUntil.current=Math.max(animateUntil.current,performance.now()+seconds*1000+35);cancelAnimationFrame(raf.current);raf.current=requestAnimationFrame(()=>sync.current());};
  const start=(e:PointerEvent)=>{if((e.target as Element).closest('.panzoom-exclude')){drag.current.active=false;return;}takeOver();drag.current={x:e.clientX,y:e.clientY,moved:false,active:true};setChooser(null);setPreview(null);};
  const motion=(e:PointerEvent)=>{if(drag.current.active&&Math.hypot(e.clientX-drag.current.x,e.clientY-drag.current.y)>6)drag.current.moved=true;};
  const end=()=>{if(drag.current.active&&drag.current.moved)suppress.current=performance.now()+220;drag.current.active=false;};
  const wheel=(e:WheelEvent)=>{if((e.target as Element).closest('.panzoom-exclude'))return;takeOver();api.zoomWithWheel(e);};
  const settled=(e:TransitionEvent)=>{if(e.target===el&&e.propertyName==='transform'){animateUntil.current=0;sync.current();}};
  el.addEventListener('panzoomchange',change);parent.addEventListener('wheel',wheel,{passive:false});parent.addEventListener('pointerdown',start,true);parent.addEventListener('pointermove',motion);parent.addEventListener('pointerup',end,true);
  el.addEventListener('transitionend',settled);
  const observer=new ResizeObserver(()=>{const next={width:parent.clientWidth,height:parent.clientHeight};if(!next.width||!next.height)return;const old=size.current;if(next.width===old.width&&next.height===old.height)return;const current=resizedCamera(camera.current,old,next);if(saved.current)saved.current=resizedCamera(saved.current,old,next);if(readingCamera.current)readingCamera.current=resizedCamera(readingCamera.current,old,next);size.current=next;fit();move(current,false);cancelAnimationFrame(layoutRaf.current);layoutRaf.current=requestAnimationFrame(()=>{avoidPaper();sync.current();});});observer.observe(parent);
  return()=>{observer.disconnect();api.destroy();el.removeEventListener('panzoomchange',change);el.removeEventListener('transitionend',settled);parent.removeEventListener('wheel',wheel);parent.removeEventListener('pointerdown',start,true);parent.removeEventListener('pointermove',motion);parent.removeEventListener('pointerup',end,true);cancelAnimationFrame(raf.current);cancelAnimationFrame(layoutRaf.current);pz.current=null;};
 },[]);
 useEffect(()=>{const old=previous.current;if(!old.selected&&selected){saved.current={...camera.current};focus(selected);}else if(selected&&selected!==old.selected)focus(selected);else if(!selected&&old.selected&&saved.current){move(saved.current);saved.current=null;readingCamera.current=null;}else if(!old.local&&local)readingCamera.current={...displayed.current};else if(old.local&&!local&&selected&&readingCamera.current)move(readingCamera.current);previous.current={selected,local,expanded};},[selected,local,expanded]);
 useEffect(()=>{cancelAnimationFrame(raf.current);raf.current=requestAnimationFrame(()=>sync.current());},[results,groups,selected,preview,chooser,workId]);
 useEffect(()=>{const sheet=document.querySelector('.reading-sheet');if(!sheet)return;const observer=new ResizeObserver(()=>{cancelAnimationFrame(layoutRaf.current);layoutRaf.current=requestAnimationFrame(()=>{avoidPaper();sync.current();});});observer.observe(sheet);const settled=()=>{avoidPaper();sync.current();};document.addEventListener('reader-settled',settled);return()=>{observer.disconnect();document.removeEventListener('reader-settled',settled);};},[selected]);
 useEffect(()=>{cancelAnimationFrame(layoutRaf.current);layoutRaf.current=requestAnimationFrame(()=>{avoidPaper();sync.current();});},[layout,expanded]);
 useEffect(()=>{const escape=(e:KeyboardEvent)=>{if(e.key==='Escape'&&(chooser||(!selected&&preview))&&!document.querySelector('dialog[open],#directory')){e.preventDefault();e.stopImmediatePropagation();if(chooser)closeChooser();setPreview(null);}};window.addEventListener('keydown',escape,true);return()=>window.removeEventListener('keydown',escape,true);},[chooser,preview,selected]);
 useEffect(()=>{if(chooser)frame.current?.querySelector<HTMLButtonElement>('.map-place-list>button')?.focus({preventScroll:true});},[chooser]);
 useEffect(()=>{if(reduced)move(camera.current,false);},[reduced]);
 const params=new URLSearchParams(location.search);const imageSrc=params.has(original?'originalFail':'overviewFail')?'assets/test-intentionally-missing.png':original?basemap.file:basemap.designFile;
 return <section className="official-overview" hidden={local} aria-label="山河探索地图" data-testid="official-overview" data-mode="image-plane">
  <div ref={frame} inert={expanded&&layout?.type==='bottom'} className="overview-viewport" data-testid="overview-viewport" aria-label="可拖动缩放的全国图面"><div ref={plane} className="overview-plane"><img className="design-map-image" src={`${import.meta.env.BASE_URL}${imageSrc}`} alt={original?'未修改的官方完整地图':'基于自然资源部标准地图原件制作的项目设计版，完整保留边界、岛屿与注记'} draggable={false} onLoad={()=>setFailed(false)} onError={()=>setFailed(true)}/></div>
   {!failed&&places.filter(p=>results.some(r=>r.place.id===p.id)||p.id===selected).map(p=><i key={p.id} data-anchor={p.id} className={`overview-anchor ${selected===p.id?'selected':''}`} aria-hidden="true"/>)}
   {!failed&&<svg className="annotation-guides" aria-hidden="true"><path className="poem-leader"/>{groups.map(g=><path key={g.id} data-label-leader={g.id} className={g.ids[0]===selected?'selected-label-leader':'label-leader'}/>)}</svg>}
   {!failed&&groups.map(g=>{const active=g.ids[0]===selected,matched=results.some(r=>r.place.id===g.ids[0]);return <button key={g.id} data-entry-id={g.id} data-place-ids={g.ids.join(',')} data-result={matched?'matched':'reading-only'} className={`overview-entry panzoom-exclude ${active?'selected':''} ${g.ids.length>1?'grouped':''}`} aria-label={`${g.ids.length===1?'地图地点':'地图分组'}：${g.label}`} aria-pressed={g.ids.length===1?active:undefined} aria-expanded={g.ids.length>1?chooser?.join(',')===g.ids.join(','):undefined} onClick={e=>{if(g.ids.length===1){if(!active)pick(results.find(r=>r.place.id===g.ids[0])!);}else{groupTrigger.current=e.currentTarget;setChooser(g.ids);}}} onMouseEnter={()=>{if(!layoutData)setPreview(g.ids[0]);}} onMouseLeave={()=>setPreview(null)} onFocus={()=>{if(!layoutData)setPreview(g.ids[0]);}} onBlur={()=>setPreview(null)}>{g.ids.length===1?(layoutData&&!publishedPlaces.some(p=>p.id===g.ids[0])?<span className="planning-symbol">规划</span>:<CategoryIcon placeId={g.ids[0]}/>):<span className="group-count">{g.ids.length}</span>}<span>{g.label}</span>{g.ids.length>1&&<small> ▾</small>}{active&&!matched&&<small className="reading-only-tag">当前阅读</small>}</button>;})}
   {failed&&<div className="overview-error panzoom-exclude" role="alert"><strong>{original?'原图':'设计地图'}未能加载</strong><p>可从目录继续读诗文，或切换图面。</p><button onClick={()=>{setOriginal(!original);setFailed(false);}}>切换到{original?'设计地图':'官方原图'}</button><button onClick={onRead}>从目录阅读</button></div>}
   <MapControls host={frame} kind="overview" onZoom={direction=>{takeOver();move({...camera.current,scale:Math.max(MIN_SCALE,Math.min(MAX_SCALE,camera.current.scale*(direction>0?1.3:1/1.3)))});}} onReset={()=>{takeOver();move({x:0,y:0,scale:1});setChooser(null);}}/>

   {chooser&&<aside className="map-place-list panzoom-exclude" aria-label="近邻地点选择"><header><span>择一处，读诗文</span><button aria-label="关闭近邻地点选择" onClick={closeChooser}>×</button></header>{chooser.map(id=>{const r=results.find(r=>r.place.id===id);return r&&<button key={id} data-place-id={id} onClick={()=>pick(r)}>{layoutData&&!publishedPlaces.some(p=>p.id===id)?<span className="planning-symbol">规划</span>:<CategoryIcon placeId={id}/>} <span><strong>{r.place.name}</strong><small>{r.place.region}</small></span></button>;})}</aside>}
   {!selected&&preview&&!chooser&&!failed&&<div className="map-poem-preview panzoom-exclude" data-preview-id={preview} role="tooltip">{(()=>{const r=relations.find(r=>r.placeId===preview)!;const w=works.find(w=>w.id===r.workId)!;return <><strong>{places.find(p=>p.id===preview)?.name}</strong><span>{shortQuote(r)}</span><small>{w.author}《{w.title}》</small></>;})()}</div>}
  </div>
 </section>;
}
