import type {RefObject} from 'react';
import {basemap} from '../data/basemap';
import {places,works,placeDetails,sources} from '../data/content';
import {CategoryIcon,iconKinds} from './CategoryIcon';
export function SourceDialog({dialog,placeId,workId,reduced,onReduced,onOriginal}:{dialog:RefObject<HTMLDialogElement|null>;placeId:string|null;workId:string;reduced:boolean;onReduced:(v:boolean)=>void;onOriginal:()=>void}){
 const place=places.find(p=>p.id===placeId);const work=place?works.find(w=>w.id===workId):undefined;const detail=placeDetails.find(d=>d.placeId===placeId);
 return <dialog ref={dialog} className="sources-dialog"><div className="dialog-header"><div><span className="eyebrow">有据可寻</span><h2>资料与来源</h2></div><button autoFocus aria-label="关闭资料与来源" onClick={()=>dialog.current?.close()}>×</button></div><label className="motion-setting"><input type="checkbox" checked={reduced} onChange={e=>onReduced(e.target.checked)}/> 减弱过渡动画（静观）</label>
 {work&&<article data-testid="current-work-source"><strong>当前作品 · {work.author}《{work.title}》</strong><p>{work.variant}</p><a href={work.source} target="_blank" rel="noreferrer">{work.sourceTitle} ↗</a><p>仅录公版古典原文，短解读为本项目原创；未复制来源的现代译文、评论或教学内容。</p></article>}
 {place&&<article><strong>{place.name} · 位置与文化来源</strong><p>{place.precision}；{place.coordinateSystem}，{place.coordinates.join(' / ')}。</p><a href={place.coordinateSource} target="_blank" rel="noreferrer">位置来源 ↗</a>{detail?.historySources.map(s=><p key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{s.title} ↗</a></p>)}<p>采用现代景区或区域位置，与作品中的地点关联；不据此认定古代建筑轮廓或作者落笔点。源坐标保持 WGS84，地图适配层将文化点与西湖全部几何一起转换为 GCJ-02；采用公开近似转换，不作测绘级精度承诺。</p></article>}
 <article id="basemap-provenance"><strong>原底图信息</strong><p>{basemap.title} · {basemap.variant}</p><p>原底图审图号：{basemap.reviewNumber}；图面署名：{basemap.imprint}。</p><p>{basemap.acquisition}</p><a href={basemap.source} target="_blank" rel="noreferrer">自然资源部标准地图服务 ↗</a><p>原始 JPG：5826 × 7249，6,827,440 字节。SHA-256：</p><code className="source-hash">{basemap.sha256}</code><button className="text-link" onClick={onOriginal}>查看官方原图 →</button></article>
 <article><strong>全国地理学习样板 · 第十一轮</strong><p>主地图由 L7 / MapLibre 绘制本地 GeoJSON 几何，全国和西湖共用一个地图实例。全国资料来自 GeoAtlas／高德，仅供学习交流，正式参赛发布许可待补；它不是官方 EPS 的衍生图，不沿用 GS(2023)2763 作为新底图审图号。</p><a href="https://help.aliyun.com/zh/datav/datav-7-0/user-guide/datav-geoatlas-widgets/" target="_blank" rel="noreferrer">GeoAtlas 来源与使用条件 ↗</a><p>按 DataV 官方坐标说明及高德来源采用 GCJ-02／Web Mercator；接口响应没有单独 CRS 字段，尚未取得针对该文件的提供方书面确认。成都、武汉、杭州与亭岛的转换数值／拓扑检查见开发记录，不代表独立测绘校验。</p><p>保留全国 35 要素（包括 100000_JD 特殊要素）与所有环、洞、岛；增加薄青设色、分级文化点与稀疏参照文字，不增加没有数据的道路或古代路线。EPS 路径存在，但尚未可靠转换和地理配准。</p><a href={`${import.meta.env.BASE_URL}legal/basemap-manifest.json`} target="_blank" rel="noreferrer">底图版本、坐标与摘要清单 ↗</a></article>
 <article><strong>历史图片与故障降级</strong><p>{basemap.changes}</p><p>第五轮 v5a 与旧 v1 设计版、原始 JPG／EPS 独立留存。当前 PNG 仅用于地图故障降级，降级明确提示；图片一般城市字无法按尺度分层，城市图片锚点不称地理配准。</p><p>历史设计版：{basemap.designFile}；SHA-256：</p><code className="source-hash">{basemap.designSha256}</code><p>西湖原始湖岸、岛洞、堤道、位置与照片来源仍为 OpenStreetMap／许可照片记录；地理源文件保持 WGS84／ODbL，仅在渲染适配层转换，原照片未改。</p><a href={`${import.meta.env.BASE_URL}legal/data-licenses.txt`} target="_blank" rel="noreferrer">本地来源与许可清单 ↗</a><a href={`${import.meta.env.BASE_URL}legal/coordtransform-MIT.txt`} target="_blank" rel="noreferrer">坐标转换参考代码 MIT 许可 ↗</a></article>
 {sources.map(s=><article key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{s.title} ↗</a><small>{s.organization}</small><p>{s.scope}</p></article>)}
 <article className="original-art-source"><strong>原创意境与地名符号</strong><p>四类地名符号为项目代码SVG。第九轮两幅AI辅助原创意境画按诗篇分别呈现：湖心亭看雪的雪夜亭舟、钱塘湖春行的春湖疏柳。图画是诗意表达，非古建复原、非实景照片，未复制馆藏影像；不是赵佶真迹或笔墨复现。旧绘画留作历史证据，黄鹤楼没有复用湖景。字体为系统宋体回退。</p><div className="icon-specimens">{places.map(p=><div key={p.id}><CategoryIcon placeId={p.id}/><span>{p.name}<small>{iconKinds[p.id]}</small></span></div>)}</div><div className="scene-specimens"><figure><img src={`${import.meta.env.BASE_URL}assets/huxin-snow-r9-v1.png`} alt="雪夜亭舟原创意境画样张，非实景"/><figcaption>湖心亭看雪 · 第九轮AI辅助原创意境画</figcaption></figure><figure><img src={`${import.meta.env.BASE_URL}assets/qiantang-spring-r9-v1.png`} alt="春湖疏柳原创意境画样张，非实景"/><figcaption>钱塘湖春行 · 第九轮AI辅助原创意境画</figcaption></figure></div><p>两幅PNG保留透明通道，本轮未修改图像。纸底paper-fibres-v5.svg为项目原创静态纤维与色差。资产、提示词与许可记录见第九轮资产台账。</p></article>
 <article className="known-gap"><strong>资料缺口与成品审核状态</strong><p>成品未送审；原底图编号不等于本项目成品已获审核。原图实际下载地址、下载时间未提供。湖心亭历次营建年表尚未完成地方志复核；本轮不开展古址精确考证。其他地点未采集新照片和局部地图，页面只显示已有资料。</p></article></dialog>;
}

