import type {RefObject} from 'react';
import {basemap} from '../data/basemap';
import {places,works,placeDetails,sources} from '../data/content';
import {CategoryIcon,iconKinds} from './CategoryIcon';
export function SourceDialog({dialog,placeId,workId,reduced,onReduced,onOriginal}:{dialog:RefObject<HTMLDialogElement|null>;placeId:string|null;workId:string;reduced:boolean;onReduced:(v:boolean)=>void;onOriginal:()=>void}){
 const place=places.find(p=>p.id===placeId);const work=place?works.find(w=>w.id===workId):undefined;const detail=placeDetails.find(d=>d.placeId===placeId);
 return <dialog ref={dialog} className="sources-dialog"><div className="dialog-header"><div><span className="eyebrow">有据可寻</span><h2>资料与来源</h2></div><button autoFocus aria-label="关闭资料与来源" onClick={()=>dialog.current?.close()}>×</button></div><label className="motion-setting"><input type="checkbox" checked={reduced} onChange={e=>onReduced(e.target.checked)}/> 减弱过渡动画（静观）</label>
 {work&&<article data-testid="current-work-source"><strong>当前作品 · {work.author}《{work.title}》</strong><p>{work.variant}</p><a href={work.source} target="_blank" rel="noreferrer">{work.sourceTitle} ↗</a><p>仅录公版古典原文，短解读为本项目原创；未复制来源的现代译文、评论或教学内容。</p></article>}
 {place&&<article><strong>{place.name} · 位置与文化来源</strong><p>{place.precision}；{place.coordinateSystem}，{place.coordinates.join(' / ')}。</p><a href={place.coordinateSource} target="_blank" rel="noreferrer">位置来源 ↗</a>{detail?.historySources.map(s=><p key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{s.title} ↗</a></p>)}<p>采用现代景区或区域位置，与作品中的地点关联；不据此认定古代建筑轮廓或作者落笔点。全国图片锚点为城市区域入口，不是经纬度配准。</p></article>}
 <article id="basemap-provenance"><strong>原底图信息</strong><p>{basemap.title} · {basemap.variant}</p><p>原底图审图号：{basemap.reviewNumber}；图面署名：{basemap.imprint}。</p><p>{basemap.acquisition}</p><a href={basemap.source} target="_blank" rel="noreferrer">自然资源部标准地图服务 ↗</a><p>原始 JPG：5826 × 7249，6,827,440 字节。SHA-256：</p><code className="source-hash">{basemap.sha256}</code><button className="text-link" onClick={onOriginal}>查看官方原图 →</button></article>
 <article><strong>项目设计版与呈现方式</strong><p>{basemap.changes}</p><p>第五轮选择独立v5a设计版，完整画幅与全部原几何保留；旧v1设计版与原件独立留存。一般城市仍嵌在图片中，未声称按尺度隐藏或完成EPS矢量整理。</p><p>设计版文件：{basemap.designFile}；SHA-256：</p><code className="source-hash">{basemap.designSha256}</code><p>西湖局部由 L7 / MapLibre 呈现，数据为 OpenStreetMap 的现代湖岸、岛屿与堤道，WGS84 / ODbL；复用一个按需创建的局部地图实例。全国用原图平面坐标，未做经纬度配准。</p><a href={`${import.meta.env.BASE_URL}legal/data-licenses.txt`} target="_blank" rel="noreferrer">本地来源与许可清单 ↗</a></article>
 {sources.map(s=><article key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{s.title} ↗</a><small>{s.organization}</small><p>{s.scope}</p></article>)}
 <article className="original-art-source"><strong>原创意境与地名符号</strong><p>四类地名符号为项目代码SVG。第九轮两幅AI辅助原创意境画按诗篇分别呈现：湖心亭看雪的雪夜亭舟、钱塘湖春行的春湖疏柳。图画是诗意表达，非古建复原、非实景照片，未复制馆藏影像；不是赵佶真迹或笔墨复现。旧绘画留作历史证据，黄鹤楼没有复用湖景。字体为系统宋体回退。</p><div className="icon-specimens">{places.map(p=><div key={p.id}><CategoryIcon placeId={p.id}/><span>{p.name}<small>{iconKinds[p.id]}</small></span></div>)}</div><div className="scene-specimens"><figure><img src={`${import.meta.env.BASE_URL}assets/huxin-snow-r9-v1.png`} alt="雪夜亭舟原创意境画样张，非实景"/><figcaption>湖心亭看雪 · 第九轮AI辅助原创意境画</figcaption></figure><figure><img src={`${import.meta.env.BASE_URL}assets/qiantang-spring-r9-v1.png`} alt="春湖疏柳原创意境画样张，非实景"/><figcaption>钱塘湖春行 · 第九轮AI辅助原创意境画</figcaption></figure></div><p>两幅PNG保留透明通道，本轮未修改图像。纸底paper-fibres-v5.svg为项目原创静态纤维与色差。资产、提示词与许可记录见第九轮资产台账。</p></article>
 <article className="known-gap"><strong>资料缺口与成品审核状态</strong><p>成品未送审；原底图编号不等于本项目成品已获审核。原图实际下载地址、下载时间未提供。湖心亭历次营建年表尚未完成地方志复核；本轮不开展古址精确考证。其他地点未采集新照片和局部地图，页面只显示已有资料。</p></article></dialog>;
}

